*Results updated 2016-08-23

*Simple logistic regressions of 1st quarter recent incarceration:

logit recentincar_qu1 age
logit recentincar_qu1 white
logit recentincar_qu1 black
logit recentincar_qu1 latino
logit recentincar_qu1 asian_and_other
logit recentincar_qu1 english
logit recentincar_qu1 male
logit recentincar_qu1 heterosexual
logit recentincar_qu1 married
logit recentincar_qu1 alone
logit recentincar_qu1 homeless
logit recentincar_qu1 hsdiploma
logit recentincar_qu1 employed
logit recentincar_qu1 mentaldiag
logit recentincar_qu1 injectdrugs
logit recentincar_qu1 everalcintox
logit recentincar_qu1 everheroin
logit recentincar_qu1 evermethadone 
logit recentincar_qu1 everotherpk 
logit recentincar_qu1 eversedative 
logit recentincar_qu1 evercocaine
logit recentincar_qu1 evermarijuana
logit recentincar_qu1 everanyopioid
logit recentincar_qu1 recentalcintox
logit recentincar_qu1 recentheroin
logit recentincar_qu1 recentmethadone
logit recentincar_qu1 recentotherpk
logit recentincar_qu1 recentsedative
logit recentincar_qu1 recentcocaine
logit recentincar_qu1 recentmarijuana
logit recentincar_qu1 years_any_opioid
logit recentincar_qu1 overdosed
logit recentincar_qu1 treatedfordrugs
logit recentincar_qu1 recentmethadonetx
logit recentincar_qu1 everincar_base
logit recentincar_qu1 recentincar_base
logit recentincar_qu1 charges_base
logit recentincar_qu1 dtxq1
logit recentincar_qu1 retention1q
**asian_and_other, homeless, recentheroin, recentsedative, recentincar_base

*Simple logistic regressions of 2nd quarter recent incarceration:

logit recentincar_qu2 age
logit recentincar_qu2 white
logit recentincar_qu2 black
logit recentincar_qu2 latino
logit recentincar_qu2 asian_and_other
logit recentincar_qu2 english
logit recentincar_qu2 male
logit recentincar_qu2 heterosexual
logit recentincar_qu2 married
logit recentincar_qu2 alone
logit recentincar_qu2 homeless
logit recentincar_qu2 hsdiploma
logit recentincar_qu2 employed
logit recentincar_qu2 mentaldiag
logit recentincar_qu2 injectdrugs
logit recentincar_qu2 everalcintox
logit recentincar_qu2 everheroin
logit recentincar_qu2 evermethadone 
logit recentincar_qu2 everotherpk 
logit recentincar_qu2 eversedative 
logit recentincar_qu2 evercocaine
logit recentincar_qu2 evermarijuana
logit recentincar_qu2 everanyopioid
logit recentincar_qu2 recentalcintox
logit recentincar_qu2 recentheroin
logit recentincar_qu2 recentmethadone
logit recentincar_qu2 recentotherpk
logit recentincar_qu2 recentsedative
logit recentincar_qu2 recentcocaine
logit recentincar_qu2 recentmarijuana
logit recentincar_qu2 years_any_opioid
logit recentincar_qu2 overdosed
logit recentincar_qu2 treatedfordrugs
logit recentincar_qu2 recentmethadonetx
logit recentincar_qu2 everincar_base
logit recentincar_qu2 recentincar_base
logit recentincar_qu2 charges_base
logit recentincar_qu2 dtxq1
logit recentincar_qu2 dtxq2
logit recentincar_qu2 retention1q
logit recentincar_qu2 retention2q
**male, recentcocaine, recentmarijuana, dtxq1, dtxq2, retention1q, retention2q

*Simple logistic regressions of 3rd quarter recent incarceration:

logit recentincar_qu3 age
logit recentincar_qu3 white
logit recentincar_qu3 black
logit recentincar_qu3 latino
logit recentincar_qu3 asian_and_other
logit recentincar_qu3 english
logit recentincar_qu3 male
logit recentincar_qu3 heterosexual
logit recentincar_qu3 married
logit recentincar_qu3 alone
logit recentincar_qu3 homeless
logit recentincar_qu3 hsdiploma
logit recentincar_qu3 employed
logit recentincar_qu3 mentaldiag
logit recentincar_qu3 injectdrugs
logit recentincar_qu3 everalcintox
logit recentincar_qu3 everheroin
logit recentincar_qu3 evermethadone 
logit recentincar_qu3 everotherpk 
logit recentincar_qu3 eversedative 
logit recentincar_qu3 evercocaine
logit recentincar_qu3 evermarijuana
logit recentincar_qu3 everanyopioid
logit recentincar_qu3 recentalcintox
logit recentincar_qu3 recentheroin
logit recentincar_qu3 recentmethadone
logit recentincar_qu3 recentotherpk
logit recentincar_qu3 recentsedative
logit recentincar_qu3 recentcocaine
logit recentincar_qu3 recentmarijuana
logit recentincar_qu3 years_any_opioid
logit recentincar_qu3 overdosed
logit recentincar_qu3 treatedfordrugs
logit recentincar_qu3 recentmethadonetx
logit recentincar_qu3 everincar_base
logit recentincar_qu3 recentincar_base
logit recentincar_qu3 charges_base
logit recentincar_qu3 dtxq1
logit recentincar_qu3 dtxq2
logit recentincar_qu3 dtxq3
logit recentincar_qu3 retention1q
logit recentincar_qu3 retention2q
logit recentincar_qu3 retention3q
**asian_and_other, english, everheroin, dtxq3

*Simple logistic regressions of 4th quarter recent incarceration:

logit recentincar_qu4 age
logit recentincar_qu4 white
logit recentincar_qu4 black
logit recentincar_qu4 latino
logit recentincar_qu4 asian_and_other
logit recentincar_qu4 english
logit recentincar_qu4 male
logit recentincar_qu4 heterosexual
logit recentincar_qu4 married
logit recentincar_qu4 alone
logit recentincar_qu4 homeless
logit recentincar_qu4 hsdiploma
logit recentincar_qu4 employed
logit recentincar_qu4 mentaldiag
logit recentincar_qu4 injectdrugs
logit recentincar_qu4 everalcintox
logit recentincar_qu4 everheroin
logit recentincar_qu4 evermethadone 
logit recentincar_qu4 everotherpk 
logit recentincar_qu4 eversedative 
logit recentincar_qu4 evercocaine
logit recentincar_qu4 evermarijuana
logit recentincar_qu4 everanyopioid
logit recentincar_qu4 recentalcintox
logit recentincar_qu4 recentheroin
logit recentincar_qu4 recentmethadone
logit recentincar_qu4 recentotherpk
logit recentincar_qu4 recentsedative
logit recentincar_qu4 recentcocaine
logit recentincar_qu4 recentmarijuana
logit recentincar_qu4 years_any_opioid
logit recentincar_qu4 overdosed
logit recentincar_qu4 treatedfordrugs
logit recentincar_qu4 recentmethadonetx
logit recentincar_qu4 everincar_base
logit recentincar_qu4 recentincar_base
logit recentincar_qu4 charges_base
logit recentincar_qu4 dtxq1
logit recentincar_qu4 dtxq2
logit recentincar_qu4 dtxq3
logit recentincar_qu4 dtxq4
logit recentincar_qu4 retention1q
logit recentincar_qu4 retention2q
logit recentincar_qu4 retention3q
logit recentincar_qu4 retention4q
**recentcocaine, years_any_opioid, dtxq2, dtxq3, dtxq4, retention1q, retention2q, retention3q, retention4q

*Simple logistic regressions of 1st quarter charges:

logit charges_qu1 age
logit charges_qu1 white
logit charges_qu1 black
logit charges_qu1 latino
logit charges_qu1 asian_and_other
logit charges_qu1 english
logit charges_qu1 male
logit charges_qu1 heterosexual
logit charges_qu1 married
logit charges_qu1 alone
logit charges_qu1 homeless
logit charges_qu1 hsdiploma
logit charges_qu1 employed
logit charges_qu1 mentaldiag
logit charges_qu1 injectdrugs
logit charges_qu1 everalcintox
logit charges_qu1 everheroin
logit charges_qu1 evermethadone 
logit charges_qu1 everotherpk 
logit charges_qu1 eversedative 
logit charges_qu1 evercocaine
logit charges_qu1 evermarijuana
logit charges_qu1 everanyopioid
logit charges_qu1 recentalcintox
logit charges_qu1 recentheroin
logit charges_qu1 recentmethadone
logit charges_qu1 recentotherpk
logit charges_qu1 recentsedative
logit charges_qu1 recentcocaine
logit charges_qu1 recentmarijuana
logit charges_qu1 years_any_opioid
logit charges_qu1 overdosed
logit charges_qu1 treatedfordrugs
logit charges_qu1 recentmethadonetx
logit charges_qu1 everincar_base
logit charges_qu1 recentincar_base
logit charges_qu1 charges_base
logit charges_qu1 dtxq1
logit charges_qu1 retention1q
**evercocaine

*Simple logistic regressions of 2nd quarter charges:

logit charges_qu2 age
logit charges_qu2 white
logit charges_qu2 black
logit charges_qu2 latino
logit charges_qu2 asian_and_other
logit charges_qu2 english
logit charges_qu2 male
logit charges_qu2 heterosexual
logit charges_qu2 married
logit charges_qu2 alone
logit charges_qu2 homeless
logit charges_qu2 hsdiploma
logit charges_qu2 employed
logit charges_qu2 mentaldiag
logit charges_qu2 injectdrugs
logit charges_qu2 everalcintox
logit charges_qu2 everheroin
logit charges_qu2 evermethadone 
logit charges_qu2 everotherpk 
logit charges_qu2 eversedative 
logit charges_qu2 evercocaine
logit charges_qu2 evermarijuana
logit charges_qu2 everanyopioid
logit charges_qu2 recentalcintox
logit charges_qu2 recentheroin
logit charges_qu2 recentmethadone
logit charges_qu2 recentotherpk
logit charges_qu2 recentsedative
logit charges_qu2 recentcocaine
logit charges_qu2 recentmarijuana
logit charges_qu2 years_any_opioid
logit charges_qu2 overdosed
logit charges_qu2 treatedfordrugs
logit charges_qu2 recentmethadonetx
logit charges_qu2 everincar_base
logit charges_qu2 recentincar_base
logit charges_qu2 charges_base
logit charges_qu2 dtxq1
logit charges_qu2 dtxq2
logit charges_qu2 retention1q
logit charges_qu2 retention2q
**age, asian_and_other

*Simple logistic regressions of 3rd quarter charges:

logit charges_qu3 age
logit charges_qu3 white
logit charges_qu3 black
logit charges_qu3 latino
logit charges_qu3 asian_and_other
logit charges_qu3 english
logit charges_qu3 male
logit charges_qu3 heterosexual
logit charges_qu3 married
logit charges_qu3 alone
logit charges_qu3 homeless
logit charges_qu3 hsdiploma
logit charges_qu3 employed
logit charges_qu3 mentaldiag
logit charges_qu3 injectdrugs
logit charges_qu3 everalcintox
logit charges_qu3 everheroin
logit charges_qu3 evermethadone 
logit charges_qu3 everotherpk 
logit charges_qu3 eversedative 
logit charges_qu3 evercocaine
logit charges_qu3 evermarijuana
logit charges_qu3 everanyopioid
logit charges_qu3 recentalcintox
logit charges_qu3 recentheroin
logit charges_qu3 recentmethadone
logit charges_qu3 recentotherpk
logit charges_qu3 recentsedative
logit charges_qu3 recentcocaine
logit charges_qu3 recentmarijuana
logit charges_qu3 years_any_opioid
logit charges_qu3 overdosed
logit charges_qu3 treatedfordrugs
logit charges_qu3 recentmethadonetx
logit charges_qu3 everincar_base
logit charges_qu3 recentincar_base
logit charges_qu3 charges_base
logit charges_qu3 dtxq1
logit charges_qu3 dtxq2
logit charges_qu3 dtxq3
logit charges_qu3 retention1q
logit charges_qu3 retention2q
logit charges_qu3 retention3q
**charges_base, dtxq3

*Simple logistic regressions of 4th quarter charges:

logit charges_qu4 age
logit charges_qu4 white
logit charges_qu4 black
logit charges_qu4 latino
logit charges_qu4 asian_and_other
logit charges_qu4 english
logit charges_qu4 male
logit charges_qu4 heterosexual
logit charges_qu4 married
logit charges_qu4 alone
logit charges_qu4 homeless
logit charges_qu4 hsdiploma
logit charges_qu4 employed
logit charges_qu4 mentaldiag
logit charges_qu4 injectdrugs
logit charges_qu4 everalcintox
logit charges_qu4 everheroin
logit charges_qu4 evermethadone 
logit charges_qu4 everotherpk 
logit charges_qu4 eversedative 
logit charges_qu4 evercocaine
logit charges_qu4 evermarijuana
logit charges_qu4 everanyopioid
logit charges_qu4 recentalcintox
logit charges_qu4 recentheroin
logit charges_qu4 recentmethadone
logit charges_qu4 recentotherpk
logit charges_qu4 recentsedative
logit charges_qu4 recentcocaine
logit charges_qu4 recentmarijuana
logit charges_qu4 years_any_opioid
logit charges_qu4 overdosed
logit charges_qu4 treatedfordrugs
logit charges_qu4 recentmethadonetx
logit charges_qu4 everincar_base
logit charges_qu4 recentincar_base
logit charges_qu4 charges_base
logit charges_qu4 dtxq1
logit charges_qu4 dtxq2
logit charges_qu4 dtxq3
logit charges_qu4 dtxq4
logit charges_qu4 retention1q
logit charges_qu4 retention2q
logit charges_qu4 retention3q
logit charges_qu4 retention4q
**NA
